### ISSUE TITLE
Media Library design rework

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#89]
https://www.figma.com/file/k8NhxbRRb8hm4fc1RQHms1/Media-Library?type=design&node-id=30-57434&mode=design

- [ ] Improve media uploader - https://github.com/BeaconCMS/beacon_live_admin/issues/74
- [ ] Sorting and pagination - https://github.com/BeaconCMS/beacon_live_admin/issues/21
- [ ] Filter by type - https://github.com/BeaconCMS/beacon_live_admin/issues/20
